import Head from "next/head";
import {
  UtrechtHeading,
  UtrechtParagraph,
  UtrechtSeparator,
  UtrechtButton,
  UtrechtDocument,
} from "@utrecht/component-library-react";

export default function Home() {
  return (
    <>
      <UtrechtDocument>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <UtrechtHeading level={1}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </UtrechtHeading>

          <UtrechtParagraph>
            Get started by editing <code>pages/index.js</code>
          </UtrechtParagraph>

          <div>
            <a href="https://nextjs.org/docs">
              <UtrechtHeading level={2}>Documentation &rarr;</UtrechtHeading>
              <UtrechtParagraph>
                Find in-depth information about Next.js features and API.
              </UtrechtParagraph>
            </a>

            <a href="https://nextjs.org/learn">
              <UtrechtHeading level={2}>Learn &rarr;</UtrechtHeading>
              <UtrechtParagraph>
                Learn about Next.js in an interactive course with quizzes!
              </UtrechtParagraph>
            </a>

            <a href="https://github.com/vercel/next.js/tree/master/examples">
              <UtrechtHeading level={2}>Examples &rarr;</UtrechtHeading>
              <UtrechtParagraph>
                Discover and deploy boilerplate example Next.js projects.
              </UtrechtParagraph>
            </a>

            <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
              <UtrechtHeading level={2}>Deploy &rarr;</UtrechtHeading>
              <UtrechtParagraph>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </UtrechtParagraph>
            </a>
          </div>
        </main>

        <footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by Vercel
          </a>
        </footer>
        <UtrechtSeparator></UtrechtSeparator>
        <form>
          <UtrechtButton>Click me</UtrechtButton>
        </form>
      </UtrechtDocument>
    </>
  );
}
