import Head from "next/head";
import Image from "next/image";
import {
  UtrechtHeading,
  UtrechtParagraph,
  UtrechtSeparator,
  UtrechtButton,
  UtrechtDocument,
  UtrechtPageFooter,
} from "@utrecht/web-component-library-react";
import { AlternateLangNavComponent } from "../src/AlternateLangNavComponent";

import cityScape from "../src/img/amersfoort-koppelpoort.jpg";
export default async function Home() {
  const locales = [
    {
      lang: "en",
      hrefLang: "en",
      title: "This page in English",
      textContent: "EN",
    },
    {
      lang: "nl",
      hrefLang: "nl",
      title: "Deze pagina in Nederlands",
      textContent: "NL",
    },
  ];
  return (
    <>
      <UtrechtDocument>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
          <nav>
            <AlternateLangNavComponent locales={locales} />
          </nav>
        </header>

        <main>
          <UtrechtHeading level={1}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </UtrechtHeading>

          <UtrechtParagraph>
            Get started by editing <code>pages/index.js</code>
          </UtrechtParagraph>

          <div>
            <a href="https://nextjs.org/docs">
              <UtrechtHeading level={2}>Documentation &rarr;</UtrechtHeading>
              <UtrechtParagraph>Find in-depth information about Next.js features and API.</UtrechtParagraph>
            </a>

            <a href="https://nextjs.org/learn">
              <UtrechtHeading level={2}>Learn &rarr;</UtrechtHeading>
              <UtrechtParagraph>Learn about Next.js in an interactive course with quizzes!</UtrechtParagraph>
            </a>

            <a href="https://github.com/vercel/next.js/tree/master/examples">
              <UtrechtHeading level={2}>Examples &rarr;</UtrechtHeading>
              <UtrechtParagraph>Discover and deploy boilerplate example Next.js projects.</UtrechtParagraph>
            </a>

            <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
              <UtrechtHeading level={2}>Deploy &rarr;</UtrechtHeading>
              <UtrechtParagraph>Instantly deploy your Next.js site to a public URL with Vercel.</UtrechtParagraph>
            </a>
          </div>
        </main>
        <aside>
          <figure>
            <Image src={cityScape} alt="Amersfoort, Koppelpoort" />
            <figcaption>
              <details>
                <summary>Koppelpoort in Amersfoort</summary>
                <div>
                  <div>
                    Bron: <a href="https://flickr.com/photos/aldovanzeeland/2628937998/">Aldo van Zeeland, Flickr</a>
                  </div>
                  <div>
                    Licentie:{" "}
                    <a rel="license" href="https://creativecommons.org/licenses/by-nc-nd/2.0/" hrefLang="en">
                      Creative Commons Attribution-NonCommercial-NoDerivs 2.0 Generic
                    </a>
                  </div>
                </div>
              </details>
            </figcaption>
          </figure>
        </aside>

        <footer>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by Vercel
          </a>
        </footer>
        <UtrechtSeparator></UtrechtSeparator>
        <form>
          <UtrechtButton>Click me</UtrechtButton>
        </form>
        <UtrechtPageFooter>{/* <nl-theme-switcher></nl-theme-switcher> */}</UtrechtPageFooter>
      </UtrechtDocument>
    </>
  );
}
